import 'package:flutter/material.dart';
import 'package:flutter_icons/flutter_icons.dart';
import 'package:gym_app/profile-marcfitt-page.dart';
import 'package:gym_app/profile-paige-page.dart';

class Coach{
  bool isHot;
  Widget widget;
  String imgUrl;
  String name;
  String type;
  String height;
  IconData iconDetail;
  String detail;
  String location;
  String rating;
  List<IconData> star;
  String price;

  Coach({
    @required this.isHot, 
    @required this.widget,
    @required this.imgUrl, 
    @required this.name,
    @required this.type,
    @required this.height,
    @required this.iconDetail,
    @required this.detail,
    @required this.location,
    @required this.rating,
    @required this.star,
    @required this.price,
  });
}

final listCoach = [
  Coach(
    isHot: true,
    widget: MarcProfilePage(),
    imgUrl: 'images/marc-fitt.jpg',
    name: 'Marc Fitt',
    type: 'Gym coach',
    height: '1m83',
    iconDetail: MaterialCommunityIcons.weight_kilogram,
    detail: '93kg',
    location: 'Califonia',
    rating: '(11448)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
    ],
    price: '25\$/month',
  ),
  Coach(
    isHot: true,
    widget: PaigeProfilePage(),
    imgUrl: 'images/paige-hathaway.jpg',
    name: 'Paige Hathaway',
    type: 'Gym coach',
    height: '1m67',
    iconDetail: Ionicons.ios_body,
    detail: '96-60-99',
    location: 'New York',
    rating: '(10520)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star_half_empty,
    ],
    price: '15\$/month',
  ),
  Coach(
    isHot: false,
    widget: MarcProfilePage(),
    imgUrl: 'images/street-udemy.jpg',
    name: 'Street Udemy',
    type: 'Workout coach',
    height: '1m80',
    iconDetail: MaterialCommunityIcons.weight_kilogram,
    detail: '93kg',
    location: 'London',
    rating: '(2448)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
    ],
    price: '20\$/month',
  ),

  Coach(
    isHot: false,
    widget: MarcProfilePage(),
    imgUrl: 'images/yoga-hnh.jpg',
    name: 'Ho Ngoc Ha',
    type: 'Aerobic coach',
    height: '1m68',
    iconDetail: Ionicons.ios_body,
    detail: '92-60-96',
    location: 'Ho Chi Minh',
    rating: '(2979)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star_half_empty,
    ],
    price: '23\$/month',
  ),
  Coach(
    isHot: true,
    widget: MarcProfilePage(),
    imgUrl: 'images/sergi-constance.jpg',
    name: 'Sergi Constance',
    type: 'Gym coach',
    height: '1m80',
    iconDetail: MaterialCommunityIcons.weight_kilogram,
    detail: '90kg',
    location: 'Texas',
    rating: '(9753)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
    ],
    price: '20\$/month',
  ),
  Coach(
    isHot: false,
    widget: MarcProfilePage(),
    imgUrl: 'images/lazar-angelov.jpg',
    name: 'Lazar Angelov',
    type: 'Workout coach',
    height: '1m80',
    iconDetail: MaterialCommunityIcons.weight_kilogram,
    detail: '93kg',
    location: 'Bolsa',
    rating: '(7448)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
    ],
    price: '20\$/month',
  ),
  Coach(
    isHot: false,
    widget: MarcProfilePage(),
    imgUrl: 'images/eva_andressa.jpg',
    name: 'Eva Andressa',
    type: 'Aerobic coach',
    height: '1m68',
    iconDetail: Ionicons.ios_body,
    detail: '92-60-96',
    location: 'San Francisco',
    rating: '(2979)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star_half_empty,
    ],
    price: '23\$/month',
  ),
  Coach(
    isHot: true,
    widget: MarcProfilePage(),
    imgUrl: 'images/Trang.jpg',
    name: 'Trang Le',
    type: 'Yoga coach',
    height: '1m65',
    iconDetail: Ionicons.ios_body,
    detail: '98-60-99',
    location: 'Ho Chi Minh',
    rating: '(7979)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star_half_empty,
    ],
    price: '10\$/month',
  ),
  Coach(
    isHot: false,
    widget: MarcProfilePage(),
    imgUrl: 'images/cellena-fox.jpg',
    name: 'Cellena Fox',
    type: 'Yoga coach',
    height: '1m70',
    iconDetail: Ionicons.ios_body,
    detail: '102-60-105',
    location: 'Las Vegas',
    rating: '(4979)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star_half_empty,
    ],
    price: '18\$/month',
  ),
  Coach(
    isHot: false,
    widget: MarcProfilePage(),
    imgUrl: 'images/aerobic-tw.jpg',
    name: 'Taylor Swift',
    type: 'Aerobic coach',
    height: '1m68',
    iconDetail: Ionicons.ios_body,
    detail: '92-60-96',
    location: 'Hollywood',
    rating: '(9979)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star_half_empty,
    ],
    price: '29\$/month',
  ),
  Coach(
    isHot: false,
    widget: MarcProfilePage(),
    imgUrl: 'images/gym-thor.jpeg',
    name: 'Thor',
    type: 'Workout coach',
    height: '1m80',
    iconDetail: MaterialCommunityIcons.weight_kilogram,
    detail: '93kg',
    location: 'Avenger',
    rating: '(4448)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
    ],
    price: '20\$/month',
  ),
  Coach(
    isHot: false,
    widget: MarcProfilePage(),
    imgUrl: 'images/jen-selter.jpg',
    name: 'Jen Selter',
    type: 'Yoga coach',
    height: '1m70',
    iconDetail: Ionicons.ios_body,
    detail: '92-60-96',
    location: 'Las Vegas',
    rating: '(4979)',
    star: [
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star,
      FontAwesome.star_half_empty,
    ],
    price: '19\$/month',
  ),
];